### PR TITLE
Added global minor mode and requisites

### PR DESCRIPTION
**Pull request by FossiFoo**
* Minor global mode (coverlay-mode)
  * Watch lcov file for changes (coverlay-watch-file)
  * Update overlays on file visit
  * Bind toggle to shortcut (C-c l)

### CODE REVIEW

**Comment by twada** [comment]
Hi @FossiFoo, thank you so much for the very  very cool feature!

I tried to use your new feature and got an error as below.
```
Debugger entered--Lisp error: (file-notify-error "No file notification package available")
  signal(file-notify-error ("No file notification package available"))
  file-notify-add-watch("~/src/github.com/power-assert-js/empower/coverage.lcov" (change) coverlay-watch-callback)
  (setq coverlay--watch-descriptor (file-notify-add-watch filepath (quote (change)) (function coverlay-watch-callback)))
  coverlay-watch-file("~/src/github.com/power-assert-js/empower/coverage.lcov")
  call-interactively(coverlay-watch-file record nil)
  command-execute(coverlay-watch-file record)
  execute-extended-command(nil "coverlay-watch-file")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

I'm using `GNU Emacs 24.5.4 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) of 2015-05-18 on Atago.local`. 

Is there any instructions to follow?
Or need some feature detection conditionals?

**Comment by FossiFoo** [comment]
oh, apparently file notification is not available on OSX (yet?): https://emacs.stackexchange.com/questions/3866/file-notify-support-on-osx

i guess i will need to detect that then.

**Comment by twada** [comment]
@FossiFoo Would you add feature detection into your pull-request? I'll use it ASAP.

**Comment by FossiFoo** [comment]
sure. i'm currently moving, so it might take another week or so :)

**Comment by twada** [comment]
Thanks! I'm looking forward to seeing it :)

**Comment by FossiFoo** [comment]
Wow, apparently this is stacking up anything i have pushed to my master. That is not what i expected. :)
Anyhow, feature detection is in the first patchset. Feel free to add it and/or anything else you like.

BTW: how do you feel about using dash.el for parsing/list handling? it seems to be a pretty common dependency for "current" emacs libraries and car/cdr/cons/assoc are slowly driving me insane ;).

Also, how do you feel about putting coverlay into ELPA? It would certainly attract more usage there and would be much easier to find.

**Comment by twada** [comment]
> Wow, apparently this is stacking up anything i have pushed to my master. That is not what i expected. :)
Anyhow, feature detection is in the first patchset. Feel free to add it and/or anything else you like.

Never mind!
Your commits looks nice to me.  Even more, you have improved my poor docs. Thanks a lot!

I admire your work and I want you to be a co-maintainer of my coverlay.el.

One thing to care about is that your master branch adds tons of new functionality and some BC breaking changes. According to [semver](http://semver.org/), it's a major bump.
So, if you agree with me, you are now developing coverlay.el 2.0.0 ;)
I'll release current coverlay as version 1.0.0.

What do you think?

> BTW: how do you feel about using dash.el for parsing/list handling? it seems to be a pretty common dependency for "current" emacs libraries and car/cdr/cons/assoc are slowly driving me insane ;).

Agreed. `dash.el` looks fine to me. Feel free to go ahead ;)

> Also, how do you feel about putting coverlay into ELPA? It would certainly attract more usage there and would be much easier to find.

Ditto. I'll register and publish to ELPA.

**Comment by CestDiego** [comment]
Is there more intent to merge this? I can do the MELPA part if people have not much time

**Comment by FossiFoo** [comment]
i can do a version bump and send a new PR over the weekend

**Comment by twada** [comment]
@FossiFoo @CestDiego I don't have much time and I need your help. Thank you guys!

**Comment by FossiFoo** [comment]
Done. Inclusion in MELPA would be great. As far as i could tell this is the only standalone coverage display for emacs, so it should be useful for a lot of people.

**Comment by twada** [comment]
@FossiFoo Looks great to me. Thanks a lot!

**Pull request merged**
