### PR TITLE
Change key bindings from reserved C-c l to M-o

### PR DESCRIPTION
**Pull request by kytwb**
refs https://github.com/twada/coverlay.el/issues/6 and https://github.com/melpa/melpa/pull/3851

### CODE REVIEW

**Comment by twada** [comment]
@kytwb Thanks!
@FossiFoo @syohex What do you think about this pull-req?

**Comment by kytwb** [comment]
Just to explain how I choose those keys, I used `unbound.el` to check for available key bindings; kept the previous bindings last letter, but changed the one for toggling from `l` to `t`.

**Comment by syohex** [comment]
I suppose `C-c C-l` prefix is better than `M-o` prefix. Meta key prefix is not usually used and `M-o` is bound to `facemenu-keymap` by default.

**Comment by kytwb** [comment]
@syohex Updated accordingly.

**Comment by twada** [comment]
@kytwb Thanks for the update. Sorry for my delay.
@syohex Thank you for your review!!

I've tried it in my emacs and found that your change does not affect key sequences.
`(define-key map (kbd "C-c C-l l") ...)` acts just as same as `C-c ll`.

And [what @purcell said here](https://github.com/melpa/melpa/pull/3851) is that we should not use `C-c C-l l` either?

> Don’t define C-c letter as a key in Lisp programs. Sequences consisting of C-c and a letter (either upper or lower case) are reserved for users; they are the only sequences reserved for users, so do not block them.
https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html

Hmm, I'm confused a bit.

**Comment by syohex** [comment]
> I've tried it in my emacs and found that your change does not affect key sequences.
(define-key map (kbd "C-c C-l l") ...) acts just as same as C-c ll

Did you restart emacs ? 

> And what @purcell said here is that we should not use C-c C-l l either?

No. We can use `C-c C-l l`. For example python-mode which is standard library binds `C-c C-t c`, `C-c C-t d` etc. Emacs does not recommend `C-c` single character key prefixes, like `C-c l`. So we can use `C-c C-l` without problems.

**Comment by twada** [comment]
> Did you restart emacs ?

Ah, just restarted and worked as expected. Thanks @syohex !
(I used `unload-feature` at that time and now learned that it's not appropriate for testing)

> Emacs does not recommend C-c single character key prefixes, like C-c l. So we can use C-c C-l without problems.

Thanks again. That clears things up a lot.

Now I'm going to merge this one. Many thanks to @kytwb.

**Pull request merged**
